import Link from "next/link";
import { ArrowRight, CircleHelp, CreditCard, LifeBuoy, LockKeyhole, ReceiptText, WalletCards } from "lucide-react";
import { PublicPage } from "../components/PublicChrome";

export const metadata = { title: "Masanawa Help Center", description: "Help with Masanawa wallets, payments, services, security and transactions." };
const topics = [
  [WalletCards,"Wallet & funding","Funding requests, virtual accounts, wallet balances and bank transfers."],
  [CreditCard,"Transfers & withdrawals","Internal transfers, beneficiaries, withdrawals and payout status."],
  [ReceiptText,"Transactions & receipts","Finding transaction references, status meanings and downloadable records."],
  [LockKeyhole,"Security & access","Passwords, transaction PINs, sessions, verification and account closure."],
] as const;
export default function HelpPage(){return <PublicPage><section className="mx-auto max-w-6xl px-5 py-16 md:px-8 lg:py-24"><div className="max-w-3xl"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-cyan-300/9 text-cyan-300"><CircleHelp size={22}/></div><h1 className="mt-6 text-4xl font-extrabold tracking-[-.05em] md:text-5xl">How can we help?</h1><p className="muted mt-5 text-sm leading-7">Start with the topic that matches what you are trying to do. Signed-in users can also open a support case from inside Masanawa so the conversation stays attached to the account.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2">{topics.map(([Icon,title,text])=><article key={title} className="rounded-[28px] border border-white/7 bg-white/[.025] p-6"><Icon size={20} className="text-cyan-300"/><h2 className="mt-4 text-base font-bold">{title}</h2><p className="muted mt-2 text-xs leading-6">{text}</p></article>)}</div><div className="mt-12 grid gap-4 md:grid-cols-2"><div className="rounded-[28px] border border-cyan-300/12 bg-cyan-300/[.045] p-6"><LifeBuoy size={20} className="text-cyan-300"/><h2 className="mt-4 text-lg font-bold">Already have an account?</h2><p className="muted mt-2 text-sm leading-7">Sign in and open a support case. You can continue the conversation from your account and see its status.</p><Link href="/profile/support" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-cyan-300">Open account support <ArrowRight size={15}/></Link></div><div className="rounded-[28px] border border-white/7 bg-white/[.025] p-6"><h2 className="text-lg font-bold">Not signed in?</h2><p className="muted mt-2 text-sm leading-7">Use the public contact page for general questions that do not require access to private account information.</p><Link href="/contact" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-cyan-300">Contact Masanawa <ArrowRight size={15}/></Link></div></div></section></PublicPage>}
