import Link from "next/link";
import { ArrowRight, LifeBuoy, Mail, MessageCircle, ShieldCheck } from "lucide-react";
import { PublicPage } from "../components/PublicChrome";

export const metadata = { title: "Contact Perfect Naira", description: "Contact Perfect Naira for product, account and support questions." };

export default function ContactPage(){
  const supportEmail = process.env.NEXT_PUBLIC_SUPPORT_EMAIL?.trim();
  return <PublicPage><section className="mx-auto max-w-5xl px-5 py-16 md:px-8 lg:py-24"><div className="max-w-3xl"><h1 className="text-4xl font-extrabold tracking-[-.05em] md:text-5xl">Talk to Perfect Naira.</h1><p className="muted mt-5 text-sm leading-7">Choose the route that matches your question. Account-specific issues are safest inside the signed-in support center because that keeps the conversation attached to your authenticated account.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3"><Card icon={LifeBuoy} title="Account support" text="Funding, transfers, withdrawals, KYC, security or transaction issues." href="/profile/support" cta="Open support"/><Card icon={MessageCircle} title="Help center" text="Common guidance for wallets, transactions, security and supported services." href="/help" cta="Browse help"/><article className="rounded-[28px] border border-white/7 bg-white/[.025] p-6"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-emerald-400/9 text-emerald-400"><Mail size={20}/></div><h2 className="mt-5 text-base font-bold">General enquiries</h2><p className="muted mt-2 text-xs leading-6">Questions that do not require access to private account information.</p>{supportEmail?<a href={`mailto:${supportEmail}`} className="mt-5 inline-flex items-center gap-2 text-xs font-bold text-emerald-400">{supportEmail}<ArrowRight size={14}/></a>:<Link href="/help" className="mt-5 inline-flex items-center gap-2 text-xs font-bold text-emerald-400">Use the help center<ArrowRight size={14}/></Link>}</article></div><div className="mt-10 flex gap-3 rounded-2xl border border-amber-300/15 bg-amber-300/[.045] p-4"><ShieldCheck size={18} className="mt-0.5 shrink-0 text-amber-300"/><p className="text-xs leading-6 text-amber-100/80">Never send your password, transaction PIN, BVN or private provider credentials through an unsecured message. Perfect Naira support should never ask you to reveal your transaction PIN.</p></div></section></PublicPage>
}
function Card({icon:Icon,title,text,href,cta}:{icon:typeof LifeBuoy;title:string;text:string;href:string;cta:string}){return <article className="rounded-[28px] border border-white/7 bg-white/[.025] p-6"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-emerald-400/9 text-emerald-400"><Icon size={20}/></div><h2 className="mt-5 text-base font-bold">{title}</h2><p className="muted mt-2 text-xs leading-6">{text}</p><Link href={href} className="mt-5 inline-flex items-center gap-2 text-xs font-bold text-emerald-400">{cta}<ArrowRight size={14}/></Link></article>}
