import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft, Boxes, GitBranch, ServerCog, ShieldCheck, Trash2 } from "lucide-react";
import { createClient } from "../../lib/supabase/server";
import { deleteProviderRoute, updateProduct, updateProvider, upsertProviderRoute } from "./actions";

function money(minor: number) {
  return new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", minimumFractionDigits: 2 }).format(minor / 100);
}
function dateLabel(value: string | null) { return value ? new Date(value).toLocaleString("en-NG") : "Never"; }

export default async function AdminPage({ searchParams }: { searchParams?: Promise<{ error?: string; message?: string }> }) {
  const params = (await searchParams) ?? {};
  const supabase = await createClient();
  const { data: claimsData } = await supabase.auth.getClaims();
  if (!claimsData?.claims?.sub) redirect("/login");
  const { data: admin } = await supabase.rpc("is_admin");
  if (!admin) redirect("/");

  const [{ data: providers }, { data: products }, { data: routes }] = await Promise.all([
    supabase.from("providers").select("id,code,name,category,active,priority,consecutive_failures,circuit_open_until,last_success_at,last_failure_at,updated_at").order("category").order("priority"),
    supabase.from("service_products").select("id,product_code,display_name,network,service_type,amount_minor,pricing_mode,min_amount_minor,max_amount_minor,active").order("service_type").order("network").order("amount_minor").limit(100),
    supabase.from("provider_product_routes").select("id,product_id,provider_id,provider_service_id,provider_product_code,provider_cost_minor,priority,active,updated_at").order("priority").limit(200),
  ]);

  const providerById = new Map((providers ?? []).map(p => [p.id, p]));
  const productById = new Map((products ?? []).map(p => [p.id, p]));

  return <main className="min-h-screen px-5 py-6 md:px-8 lg:px-12 lg:py-10"><div className="mx-auto max-w-7xl">
    <div className="flex items-center gap-4"><Link href="/" className="flex h-10 w-10 items-center justify-center rounded-2xl border border-white/8 bg-white/[.035]"><ArrowLeft size={18}/></Link><div><div className="flex items-center gap-2"><ShieldCheck size={18} className="text-emerald-400"/><h1 className="text-2xl font-extrabold tracking-[-.035em]">Perfect Naira Admin</h1></div><p className="muted mt-1 text-xs">Provider routing, circuit health and service catalog controls.</p></div></div>
    {params.error && <div className="mt-6 rounded-2xl border border-rose-400/20 bg-rose-400/8 px-4 py-3 text-sm text-rose-200">{params.error}</div>}
    {params.message && <div className="mt-6 rounded-2xl border border-emerald-400/20 bg-emerald-400/8 px-4 py-3 text-sm text-emerald-200">{params.message}</div>}

    <section className="panel mt-7 rounded-[30px] p-5 md:p-6"><div className="flex items-center gap-3"><ServerCog size={20} className="text-emerald-400"/><div><h2 className="font-bold">Providers</h2><p className="muted mt-1 text-xs">Traffic only routes to active providers whose circuit is closed.</p></div></div><div className="mt-5 grid gap-4 lg:grid-cols-2">{(providers ?? []).map(provider => {
      const circuitOpen = Boolean(provider.circuit_open_until && new Date(provider.circuit_open_until).getTime() > Date.now());
      return <form action={updateProvider} key={provider.code} className="soft-panel rounded-2xl p-4"><input type="hidden" name="code" value={provider.code}/><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-bold">{provider.name}</p><p className="muted mt-1 text-[11px]">{provider.code} · {provider.category}</p></div><div className="flex items-center gap-2"><span className={`rounded-full border px-2.5 py-1 text-[10px] font-semibold ${circuitOpen ? "border-rose-300/20 bg-rose-300/[.07] text-rose-300" : "border-emerald-300/20 bg-emerald-300/[.07] text-emerald-300"}`}>{circuitOpen ? "CIRCUIT OPEN" : "HEALTHY ROUTE"}</span><label className="flex items-center gap-2 text-xs"><input type="checkbox" name="active" defaultChecked={provider.active} className="accent-emerald-400"/> Active</label></div></div><div className="mt-4 grid grid-cols-2 gap-3 text-[11px] text-slate-400 sm:grid-cols-4"><div><p className="text-slate-500">Failures</p><p className="mt-1 font-semibold text-slate-200">{provider.consecutive_failures}</p></div><div><p className="text-slate-500">Last success</p><p className="mt-1 text-slate-200">{dateLabel(provider.last_success_at)}</p></div><div><p className="text-slate-500">Last failure</p><p className="mt-1 text-slate-200">{dateLabel(provider.last_failure_at)}</p></div><div><p className="text-slate-500">Circuit until</p><p className="mt-1 text-slate-200">{dateLabel(provider.circuit_open_until)}</p></div></div><div className="mt-4 flex items-end gap-3"><div className="flex-1"><label className="text-[11px] font-semibold">Priority</label><input name="priority" type="number" min="1" max="1000" defaultValue={provider.priority} className="mt-2 w-full rounded-xl border border-white/8 bg-white/[.035] px-3 py-2.5 text-sm outline-none"/></div><button className="rounded-xl bg-emerald-400 px-4 py-2.5 text-xs font-bold text-slate-950">Save</button></div></form>;
    })}</div></section>

    <section className="panel mt-5 rounded-[30px] p-5 md:p-6"><div className="flex items-center gap-3"><GitBranch size={20} className="text-emerald-400"/><div><h2 className="font-bold">Provider routes</h2><p className="muted mt-1 text-xs">Each product may have multiple provider-specific service/variation codes. Lower priority wins.</p></div></div>
      <form action={upsertProviderRoute} className="mt-5 grid gap-3 rounded-2xl border border-white/7 bg-white/[.025] p-4 md:grid-cols-2 xl:grid-cols-7"><select name="product_code" required className="rounded-xl border border-white/8 bg-[#08291d] px-3 py-2.5 text-xs"><option value="">Product</option>{(products ?? []).map(p=><option key={p.id} value={p.product_code}>{p.display_name} · {p.network || p.service_type}</option>)}</select><select name="provider_code" required className="rounded-xl border border-white/8 bg-[#08291d] px-3 py-2.5 text-xs"><option value="">Provider</option>{(providers ?? []).map(p=><option key={p.id} value={p.code}>{p.name}</option>)}</select><input name="provider_service_id" required placeholder="Service ID e.g. mtn-data" className="rounded-xl border border-white/8 bg-white/[.035] px-3 py-2.5 text-xs outline-none"/><input name="provider_product_code" placeholder="Variation code" className="rounded-xl border border-white/8 bg-white/[.035] px-3 py-2.5 text-xs outline-none"/><input name="provider_cost" type="number" min="0" step="0.01" placeholder="Provider cost NGN" className="rounded-xl border border-white/8 bg-white/[.035] px-3 py-2.5 text-xs outline-none"/><input name="priority" type="number" min="1" max="1000" defaultValue="10" className="rounded-xl border border-white/8 bg-white/[.035] px-3 py-2.5 text-xs outline-none"/><div className="flex items-center gap-3"><label className="flex items-center gap-2 text-xs"><input type="checkbox" name="active" className="accent-emerald-400"/> Active</label><button className="ml-auto rounded-xl bg-emerald-400 px-4 py-2.5 text-xs font-bold text-slate-950">Save route</button></div></form>
      <div className="mt-4 space-y-2">{(routes ?? []).length===0 ? <p className="muted py-6 text-center text-xs">No provider routes configured yet.</p> : (routes ?? []).map(route => { const provider=providerById.get(route.provider_id); const product=productById.get(route.product_id); return <div key={route.id} className="grid gap-3 rounded-2xl border border-white/7 bg-white/[.02] p-4 text-xs md:grid-cols-[1.3fr_.8fr_.9fr_.8fr_.5fr_auto]"><div><p className="font-semibold">{product?.display_name ?? route.product_id}</p><p className="muted mt-1 text-[10px]">{product?.product_code}</p></div><div><p>{provider?.name ?? route.provider_id}</p><p className="muted mt-1 text-[10px]">priority {route.priority}</p></div><div><p className="font-mono text-[11px]">{route.provider_service_id}</p><p className="muted mt-1 font-mono text-[10px]">{route.provider_product_code || "no variation"}</p></div><div><p>{route.provider_cost_minor==null ? "Cost unknown" : money(Number(route.provider_cost_minor))}</p><p className="muted mt-1 text-[10px]">updated {dateLabel(route.updated_at)}</p></div><div className="flex items-center"><span className={`rounded-full border px-2.5 py-1 text-[10px] font-semibold ${route.active?"border-emerald-300/20 bg-emerald-300/[.07] text-emerald-300":"border-slate-300/10 bg-white/[.03] text-slate-400"}`}>{route.active?"ACTIVE":"INACTIVE"}</span></div><form action={deleteProviderRoute} className="flex items-center"><input type="hidden" name="route_id" value={route.id}/><button type="submit" title="Remove route" className="flex h-9 w-9 items-center justify-center rounded-xl border border-rose-300/15 bg-rose-300/[.05] text-rose-300 transition hover:bg-rose-300/[.1]"><Trash2 size={15}/></button></form></div>; })}</div>
    </section>

    <section className="panel mt-5 rounded-[30px] p-5 md:p-6"><div className="flex items-center gap-3"><Boxes size={20} className="text-emerald-400"/><div><h2 className="font-bold">Service products</h2><p className="muted mt-1 text-xs">A product can only be activated when at least one provider route above is active.</p></div></div><div className="mt-5 space-y-3">{(products ?? []).map(product => <form action={updateProduct} key={product.product_code} className="rounded-2xl border border-white/7 bg-white/[.025] p-4"><input type="hidden" name="product_code" value={product.product_code}/><input type="hidden" name="provider_code" value=""/><input type="hidden" name="provider_product_code" value=""/><div className="grid gap-4 lg:grid-cols-[1.25fr_.65fr_.8fr_auto]"><div><p className="text-sm font-semibold">{product.display_name}</p><p className="muted mt-1 text-[11px]">{product.product_code} · {product.network || "—"} · {product.service_type} · {product.pricing_mode}</p></div><div><label className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Base price</label><input name="amount" defaultValue={(Number(product.amount_minor) / 100).toFixed(2)} className="mt-2 w-full rounded-xl border border-white/8 bg-white/[.035] px-3 py-2.5 text-xs outline-none"/><p className="muted mt-1 text-[10px]">{money(Number(product.amount_minor))}</p></div><div><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Range</p><p className="mt-2 text-xs">{product.pricing_mode==="flexible" ? `${product.min_amount_minor?money(Number(product.min_amount_minor)):"—"} → ${product.max_amount_minor?money(Number(product.max_amount_minor)):"—"}` : "Fixed by database"}</p></div><div className="flex items-end gap-3"><label className="mb-2 flex items-center gap-2 text-xs"><input type="checkbox" name="active" defaultChecked={product.active} className="accent-emerald-400"/> Active</label><button className="rounded-xl bg-emerald-400 px-4 py-2.5 text-xs font-bold text-slate-950">Save</button></div></div></form>)}</div></section>
  </div></main>;
}
