import Link from "next/link";
import { ArrowLeft, Phone, ShieldCheck } from "lucide-react";
import { createServiceOrder } from "../actions";

const networks = ["MTN", "Airtel", "Glo", "9mobile"];

export default async function AirtimePage({ searchParams }: { searchParams?: Promise<{ error?: string }> }) {
  const params = (await searchParams) ?? {};
  return <main className="min-h-screen px-5 py-6 md:px-8 lg:py-10"><div className="mx-auto max-w-2xl"><Link href="/services" className="muted inline-flex items-center gap-2 text-sm hover:text-white"><ArrowLeft size={17}/>Back to services</Link><div className="mt-7"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-cyan-300/10 text-cyan-300"><Phone size={22}/></div><h1 className="mt-5 text-2xl font-bold md:text-3xl">Buy airtime</h1><p className="muted mt-2 text-sm">Recharge any supported Nigerian mobile network.</p></div><section className="panel mt-7 rounded-[30px] p-5 md:p-7">{params.error && <div className="mb-5 rounded-2xl border border-rose-400/20 bg-rose-400/8 px-4 py-3 text-sm text-rose-200">{params.error}</div>}<form action={createServiceOrder} className="space-y-5"><input type="hidden" name="kind" value="airtime"/><input type="hidden" name="return_to" value="/services/airtime"/><div><label htmlFor="product_code" className="text-xs font-semibold">Network</label><select id="product_code" name="product_code" required defaultValue="MTN" className="mt-3 w-full rounded-2xl border border-white/8 bg-[#0d1a2a] px-4 py-3.5 text-sm outline-none focus:border-cyan-300/30">{networks.map(n=><option key={n} value={n}>{n}</option>)}</select></div><div><label htmlFor="recipient" className="block text-xs font-semibold">Phone number</label><input id="recipient" name="recipient" required inputMode="tel" pattern="[0-9+]{10,14}" placeholder="08012345678" className="mt-3 w-full rounded-2xl border border-white/8 bg-white/[.035] px-4 py-3.5 text-sm outline-none placeholder:text-slate-600 focus:border-cyan-300/30"/></div><div><label htmlFor="amount" className="block text-xs font-semibold">Amount (NGN)</label><input id="amount" name="amount" required type="number" min="50" step="50" placeholder="1000" className="mt-3 w-full rounded-2xl border border-white/8 bg-white/[.035] px-4 py-3.5 text-sm outline-none placeholder:text-slate-600 focus:border-cyan-300/30"/></div><div className="flex items-start gap-3 rounded-2xl bg-cyan-300/[.045] p-4"><ShieldCheck className="mt-0.5 shrink-0 text-cyan-300" size={17}/><p className="muted text-xs leading-5">Masanawa checks your authenticated wallet balance and creates an idempotent pending order. Your ledger is not debited until backend processing confirms the provider result.</p></div><button type="submit" className="flex w-full items-center justify-center rounded-2xl bg-cyan-300 py-3.5 text-sm font-bold text-slate-950">Create airtime order</button></form></section></div></main>;
}
