import Link from "next/link";
import { ArrowLeft, Phone, ShieldCheck } from "lucide-react";

const networks = ["MTN", "Airtel", "Glo", "9mobile"];
const amounts = ["₦500", "₦1,000", "₦2,000", "₦5,000"];

export default function AirtimePage() {
  return <main className="min-h-screen px-5 py-6 md:px-8 lg:py-10"><div className="mx-auto max-w-2xl"><Link href="/services" className="muted inline-flex items-center gap-2 text-sm hover:text-white"><ArrowLeft size={17}/>Back to services</Link><div className="mt-7"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-cyan-300/10 text-cyan-300"><Phone size={22}/></div><h1 className="mt-5 text-2xl font-bold md:text-3xl">Buy airtime</h1><p className="muted mt-2 text-sm">Recharge any supported Nigerian mobile network.</p></div><section className="panel mt-7 rounded-[30px] p-5 md:p-7"><label className="text-xs font-semibold">Network</label><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4">{networks.map((n,i)=><button key={n} className={`rounded-2xl border px-3 py-3 text-sm font-semibold ${i===0?"border-cyan-300/30 bg-cyan-300/10 text-cyan-300":"border-white/8 bg-white/[.03] text-slate-300"}`}>{n}</button>)}</div><label className="mt-6 block text-xs font-semibold">Phone number</label><input placeholder="08012345678" className="mt-3 w-full rounded-2xl border border-white/8 bg-white/[.035] px-4 py-3.5 text-sm outline-none placeholder:text-slate-600 focus:border-cyan-300/30"/><label className="mt-6 block text-xs font-semibold">Amount</label><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4">{amounts.map(a=><button key={a} className="rounded-2xl border border-white/8 bg-white/[.03] px-3 py-3 text-sm font-semibold hover:border-cyan-300/25">{a}</button>)}</div><input placeholder="Enter custom amount" className="mt-3 w-full rounded-2xl border border-white/8 bg-white/[.035] px-4 py-3.5 text-sm outline-none placeholder:text-slate-600 focus:border-cyan-300/30"/><div className="mt-6 flex items-start gap-3 rounded-2xl bg-cyan-300/[.045] p-4"><ShieldCheck className="mt-0.5 shrink-0 text-cyan-300" size={17}/><p className="muted text-xs leading-5">Confirm the phone number before payment. The backend will validate provider availability and final price before debit.</p></div><Link href="/transactions/preview" className="mt-6 flex w-full items-center justify-center rounded-2xl bg-cyan-300 py-3.5 text-sm font-bold text-slate-950">Continue</Link></section></div></main>;
}
