import Link from "next/link";
import { ArrowRight, Layers3, ShieldCheck, WalletCards } from "lucide-react";
import { PublicPage } from "../components/PublicChrome";

export const metadata = { title: "About Masanawa", description: "Learn what Masanawa is building and how the platform is designed." };

export default function AboutPage(){return <PublicPage><section className="mx-auto max-w-7xl px-5 py-16 md:px-8 lg:py-24"><div className="max-w-3xl"><h1 className="text-4xl font-extrabold tracking-[-.05em] md:text-5xl">A simpler way to manage everyday digital money.</h1><p className="muted mt-6 text-base leading-8">Masanawa is being built as one account for wallet funding, transfers, digital services, transaction history, account verification and provider-backed digital assets. The platform is designed around clear state, strong auditability and security controls instead of disconnected service screens.</p></div><div className="mt-14 grid gap-4 md:grid-cols-3"><Value icon={WalletCards} title="One account" text="Wallet, bills, transfers, rewards and digital assets live inside one coherent product."/><Value icon={ShieldCheck} title="Security by default" text="Transaction PINs, KYC-linked limits, provider verification and ledger controls are part of the transaction path."/><Value icon={Layers3} title="Built to grow" text="Provider routing, admin operations and accounting foundations are separated so new services can be added safely."/></div><div className="mt-16 rounded-[32px] border border-white/7 bg-white/[.025] p-6 md:p-9"><h2 className="text-2xl font-bold tracking-[-.03em]">What Masanawa is not</h2><p className="muted mt-4 max-w-3xl text-sm leading-7">Masanawa does not invent balances, fake provider confirmations or pretend an unavailable financial service is active. Features that require external providers are enabled only after the relevant provider path is configured and verified.</p><Link href="/security" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-cyan-300">Read about security <ArrowRight size={15}/></Link></div></section></PublicPage>}

function Value({icon:Icon,title,text}:{icon:typeof WalletCards;title:string;text:string}){return <article className="rounded-[28px] border border-white/7 bg-white/[.025] p-6"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-cyan-300/9 text-cyan-300"><Icon size={20}/></div><h2 className="mt-5 text-lg font-bold">{title}</h2><p className="muted mt-2 text-sm leading-7">{text}</p></article>}
