import Link from "next/link";
import { ArrowLeft, Mail, ShieldCheck } from "lucide-react";
import { requestPasswordReset } from "../auth/actions";

export const metadata = { title: "Reset password" };
export default async function ForgotPasswordPage({searchParams}:{searchParams?:Promise<{error?:string;message?:string}>}) {
  const params=(await searchParams)??{};
  return <main className="min-h-screen px-5 py-8 sm:px-8"><div className="mx-auto flex min-h-[calc(100vh-4rem)] max-w-md items-center"><div className="w-full"><Link href="/" className="mb-8 flex items-center gap-2.5"><img src="/masanawa-mark.svg" alt="" className="h-9 w-9"/><span className="text-base font-extrabold">Masanawa</span></Link><Link href="/login" className="muted inline-flex items-center gap-2 text-sm hover:text-white"><ArrowLeft size={17}/>Back to sign in</Link><div className="mt-10 flex h-12 w-12 items-center justify-center rounded-2xl bg-cyan-300/10 text-cyan-300"><ShieldCheck size={22}/></div><h1 className="mt-5 text-3xl font-extrabold tracking-[-.04em]">Reset your password</h1><p className="muted mt-2 text-sm leading-6">Enter your account email. If it matches an account, Masanawa will send a secure recovery link.</p>{params.error&&<div className="mt-5 rounded-2xl border border-rose-400/20 bg-rose-400/8 px-4 py-3 text-sm text-rose-200">{params.error}</div>}{params.message&&<div className="mt-5 rounded-2xl border border-emerald-400/20 bg-emerald-400/[.07] px-4 py-3 text-sm text-emerald-200">{params.message}</div>}<form action={requestPasswordReset} className="panel mt-7 rounded-[30px] p-5 md:p-6"><label htmlFor="email" className="text-xs font-semibold">Email address</label><div className="mt-3 flex h-13 items-center gap-3 rounded-2xl border border-white/9 bg-white/[.035] px-4 focus-within:border-cyan-300/35"><Mail size={17} className="text-slate-500"/><input id="email" name="email" type="email" autoComplete="email" required placeholder="you@example.com" className="h-full min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-slate-600"/></div><button className="mt-5 w-full rounded-2xl bg-cyan-300 py-3.5 text-sm font-bold text-slate-950">Send reset link</button></form></div></div></main>;
}
