import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft, KeyRound, ShieldCheck } from "lucide-react";
import { createClient } from "../../../lib/supabase/server";
import { setTransactionPin } from "./actions";

export default async function SecurityPage({ searchParams }: { searchParams?: Promise<{ error?: string; message?: string }> }) {
  const params = (await searchParams) ?? {};
  const supabase = await createClient();
  const { data: claimsData } = await supabase.auth.getClaims();
  if (!claimsData?.claims?.sub) redirect("/login");
  const { data: pinConfigured } = await supabase.rpc("has_transaction_pin");

  return <main className="min-h-screen px-5 py-6 md:px-8 lg:py-10"><div className="mx-auto max-w-2xl"><Link href="/profile" className="muted inline-flex items-center gap-2 text-sm hover:text-white"><ArrowLeft size={17}/>Back to profile</Link><div className="mt-7"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-cyan-300/10 text-cyan-300"><KeyRound size={22}/></div><h1 className="mt-5 text-2xl font-bold md:text-3xl">Security & transaction PIN</h1><p className="muted mt-2 text-sm">Protect payments with a six-digit PIN stored only as a one-way hash.</p></div>{params.error && <div className="mt-6 rounded-2xl border border-rose-400/20 bg-rose-400/8 px-4 py-3 text-sm text-rose-200">{params.error}</div>}{params.message && <div className="mt-6 rounded-2xl border border-emerald-400/20 bg-emerald-400/8 px-4 py-3 text-sm text-emerald-200">{params.message}</div>}<section className="panel mt-7 rounded-[30px] p-5 md:p-7"><div className="mb-6 flex items-center justify-between rounded-2xl border border-white/7 bg-white/[.025] p-4"><div><p className="text-sm font-semibold">Transaction PIN</p><p className="muted mt-1 text-xs">{pinConfigured ? "Configured" : "Not configured"}</p></div><span className={`rounded-full border px-3 py-1 text-[10px] font-semibold ${pinConfigured ? "border-emerald-300/20 bg-emerald-300/[.07] text-emerald-300" : "border-amber-300/20 bg-amber-300/[.07] text-amber-300"}`}>{pinConfigured ? "ACTIVE" : "REQUIRED"}</span></div><form action={setTransactionPin} className="space-y-5"><div><label htmlFor="pin" className="text-xs font-semibold">New 6-digit PIN</label><input id="pin" name="pin" required type="password" inputMode="numeric" autoComplete="new-password" pattern="[0-9]{6}" maxLength={6} placeholder="••••••" className="mt-3 w-full rounded-2xl border border-white/8 bg-white/[.035] px-4 py-3.5 text-sm tracking-[.35em] outline-none placeholder:tracking-normal placeholder:text-slate-600 focus:border-cyan-300/30"/></div><div><label htmlFor="confirm_pin" className="text-xs font-semibold">Confirm PIN</label><input id="confirm_pin" name="confirm_pin" required type="password" inputMode="numeric" autoComplete="new-password" pattern="[0-9]{6}" maxLength={6} placeholder="••••••" className="mt-3 w-full rounded-2xl border border-white/8 bg-white/[.035] px-4 py-3.5 text-sm tracking-[.35em] outline-none placeholder:tracking-normal placeholder:text-slate-600 focus:border-cyan-300/30"/></div><div className="flex gap-3 rounded-2xl bg-cyan-300/[.045] p-4"><ShieldCheck size={18} className="mt-0.5 shrink-0 text-cyan-300"/><p className="muted text-xs leading-5">Masanawa never exposes your PIN hash through the Data API. Setting a new PIN replaces the old one immediately.</p></div><button type="submit" className="flex w-full items-center justify-center rounded-2xl bg-cyan-300 py-3.5 text-sm font-bold text-slate-950">{pinConfigured ? "Change transaction PIN" : "Set transaction PIN"}</button></form></section></div></main>;
}
