import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft, KeyRound, LockKeyhole, LogOut, ShieldCheck } from "lucide-react";
import { createClient } from "../../../lib/supabase/server";
import { changePassword, setTransactionPin, signOutEverywhere } from "./actions";

export default async function SecurityPage({ searchParams }: { searchParams?: Promise<{ error?: string; message?: string }> }) {
  const params = (await searchParams) ?? {};
  const supabase = await createClient();
  const { data: claimsData } = await supabase.auth.getClaims();
  if (!claimsData?.claims?.sub) redirect("/login");
  const { data: pinConfigured } = await supabase.rpc("has_transaction_pin");

  return <div className="w-full"><div className="max-w-6xl">
    <Link href="/profile" className="muted inline-flex items-center gap-2 text-sm hover:text-white"><ArrowLeft size={17}/>Back to profile</Link>
    <div className="mt-7"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-400/10 text-emerald-400"><KeyRound size={22}/></div><h1 className="mt-5 text-2xl font-bold md:text-3xl">Security</h1><p className="muted mt-2 text-sm">Manage your account password, active sessions and six-digit transaction PIN.</p></div>
    {params.error && <div className="mt-6 rounded-2xl border border-rose-400/20 bg-rose-400/8 px-4 py-3 text-sm text-rose-200">{params.error}</div>}
    {params.message && <div className="mt-6 rounded-2xl border border-emerald-400/20 bg-emerald-400/8 px-4 py-3 text-sm text-emerald-200">{params.message}</div>}

    <section className="panel mt-7 rounded-[30px] p-5 md:p-7"><div className="mb-6 flex items-center justify-between rounded-2xl border border-white/7 bg-white/[.025] p-4"><div><p className="text-sm font-semibold">Transaction PIN</p><p className="muted mt-1 text-xs">{pinConfigured ? "Configured" : "Not configured"}</p></div><span className={`rounded-full border px-3 py-1 text-[10px] font-semibold ${pinConfigured ? "border-emerald-300/20 bg-emerald-300/[.07] text-emerald-300" : "border-amber-300/20 bg-amber-300/[.07] text-amber-300"}`}>{pinConfigured ? "ACTIVE" : "REQUIRED"}</span></div><form action={setTransactionPin} className="space-y-5"><div><label htmlFor="pin" className="text-xs font-semibold">New 6-digit PIN</label><input id="pin" name="pin" required type="password" inputMode="numeric" autoComplete="new-password" pattern="[0-9]{6}" maxLength={6} placeholder="••••••" className="mt-3 w-full rounded-2xl border border-white/8 bg-white/[.035] px-4 py-3.5 text-sm tracking-[.35em] outline-none placeholder:tracking-normal placeholder:text-slate-600 focus:border-emerald-400/30"/></div><div><label htmlFor="confirm_pin" className="text-xs font-semibold">Confirm PIN</label><input id="confirm_pin" name="confirm_pin" required type="password" inputMode="numeric" autoComplete="new-password" pattern="[0-9]{6}" maxLength={6} placeholder="••••••" className="mt-3 w-full rounded-2xl border border-white/8 bg-white/[.035] px-4 py-3.5 text-sm tracking-[.35em] outline-none placeholder:tracking-normal placeholder:text-slate-600 focus:border-emerald-400/30"/></div><div className="flex gap-3 rounded-2xl bg-emerald-400/[.045] p-4"><ShieldCheck size={18} className="mt-0.5 shrink-0 text-emerald-400"/><p className="muted text-xs leading-5">Perfect Naira never exposes your PIN hash through the Data API. Setting a new PIN replaces the old one immediately.</p></div><button type="submit" className="flex w-full items-center justify-center rounded-2xl bg-emerald-400 py-3.5 text-sm font-bold text-slate-950">{pinConfigured ? "Change transaction PIN" : "Set transaction PIN"}</button></form></section>

    <section className="panel mt-5 rounded-[30px] p-5 md:p-7"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-white/[.04] text-emerald-400"><LockKeyhole size={18}/></div><div><h2 className="text-sm font-bold">Account password</h2><p className="muted mt-1 text-xs">Use at least 8 characters and a password unique to Perfect Naira.</p></div></div><form action={changePassword} className="mt-5 grid gap-4 sm:grid-cols-2"><div><label htmlFor="password" className="text-xs font-semibold">New password</label><input id="password" name="password" type="password" autoComplete="new-password" minLength={8} required className="mt-3 w-full rounded-2xl border border-white/8 bg-white/[.035] px-4 py-3.5 text-sm outline-none focus:border-emerald-400/30"/></div><div><label htmlFor="confirm_password" className="text-xs font-semibold">Confirm password</label><input id="confirm_password" name="confirm_password" type="password" autoComplete="new-password" minLength={8} required className="mt-3 w-full rounded-2xl border border-white/8 bg-white/[.035] px-4 py-3.5 text-sm outline-none focus:border-emerald-400/30"/></div><button className="sm:col-span-2 rounded-2xl border border-emerald-400/20 bg-emerald-400/[.08] py-3.5 text-sm font-bold text-emerald-400">Change password</button></form></section>

    <section className="panel mt-5 rounded-[30px] p-5 md:p-7"><div className="flex items-start justify-between gap-4"><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-rose-300/[.07] text-rose-300"><LogOut size={18}/></div><div><h2 className="text-sm font-bold">Active sessions</h2><p className="muted mt-1 max-w-lg text-xs leading-5">If you suspect another device has access to your account, sign out every active session and sign in again on devices you trust.</p></div></div></div><form action={signOutEverywhere} className="mt-5"><button className="w-full rounded-2xl border border-rose-300/20 bg-rose-300/[.06] py-3.5 text-sm font-bold text-rose-300">Sign out all sessions</button></form></section>
  </div></div>;
}
