import { FileText } from "lucide-react";
import { PublicPage } from "../components/PublicChrome";

export const metadata = { title: "Terms of Service", description: "Terms governing use of Masanawa." };
const sections = [
  ["Using Masanawa", "You must provide accurate account information, keep your credentials and transaction PIN secure, and use Masanawa only for lawful activity. You are responsible for actions completed through an authenticated session unless you report suspected compromise promptly."],
  ["Wallet and payments", "Wallet balances are recorded through Masanawa's ledger. Funding, withdrawals and service purchases may depend on external payment or service providers. A request is not final merely because it was submitted; settlement status shown in your transaction record controls completion."],
  ["Digital services", "Airtime, data, electricity, cable, gift-card and similar products may be supplied by third-party providers. Availability, product codes and provider pricing can change. Masanawa may disable a product or provider route when it cannot be verified safely."],
  ["Crypto features", "Digital-asset features are subject to provider availability and operational controls. Quotes can change before execution, digital assets can be volatile, and Masanawa does not promise a particular market price or return. Crypto actions remain disabled when a verified execution path is unavailable."],
  ["Verification and limits", "Masanawa may require identity verification and apply configurable transaction limits or additional checks before allowing higher-risk or higher-value activity. A pending request may be delayed, rejected or reversed when required for security, provider reconciliation or compliance review."],
  ["Prohibited activity", "Do not use Masanawa for fraud, unauthorized access, laundering proceeds of crime, sanctions evasion, abusive automation, manipulation of provider systems, or transactions involving funds or accounts you are not authorized to use."],
  ["Service availability", "We aim to keep Masanawa available, but maintenance, network failures, provider outages or security controls can interrupt service. Pending transactions remain subject to their recorded status and provider reconciliation."],
  ["Changes and contact", "These terms may be updated as Masanawa's products and provider relationships change. Material changes should be reflected in the version published here. For account-specific questions, use the in-app Help & Support feature."],
] as const;

export default function TermsPage(){return <PublicPage><section className="mx-auto max-w-3xl px-5 py-16 md:px-8 lg:py-20"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-cyan-300/10 text-cyan-300"><FileText size={21}/></div><h1 className="mt-5 text-3xl font-extrabold tracking-[-.04em] md:text-4xl">Terms of Service</h1><p className="muted mt-2 text-sm">Masanawa product terms · Last updated 31 August 2026</p><div className="panel mt-7 rounded-[30px] p-5 md:p-8"><p className="text-sm leading-7 text-slate-300">These terms describe the rules for using the Masanawa application and its wallet, payment, digital-service and digital-asset features. Specific third-party services may also be subject to the relevant provider&apos;s terms.</p><div className="mt-7 divide-y divide-white/7">{sections.map(([title,body])=><section key={title} className="py-6 first:pt-0 last:pb-0"><h2 className="text-base font-bold">{title}</h2><p className="muted mt-2 text-sm leading-7">{body}</p></section>)}</div></div><p className="muted mt-6 text-xs leading-5">For questions about a transaction or account restriction, sign in and open Profile → Help & Support.</p></section></PublicPage>}
