import Link from "next/link";
import { ArrowRight, Gift, LockKeyhole, Mail, ShieldCheck, UserRound } from "lucide-react";
import { register } from "../auth/actions";

export const metadata = { title: "Create account" };
export default async function RegisterPage({ searchParams }: { searchParams?: Promise<{ error?: string; ref?: string }> }) {
  const params = (await searchParams) ?? {};
  const referralCode = (params.ref ?? "").trim().toUpperCase().slice(0,24);
  return <main className="min-h-screen px-5 py-8 sm:px-8 lg:grid lg:grid-cols-[.92fr_1.08fr] lg:p-0">
    <section className="flex min-h-[calc(100vh-4rem)] items-center justify-center lg:min-h-screen"><div className="w-full max-w-md"><Link href="/" className="mb-10 flex items-center gap-3"><img src="/masanawa-mark.svg" alt="" className="h-10 w-10"/><p className="text-lg font-extrabold">Masanawa</p></Link><p className="text-sm font-semibold text-cyan-300">Get started</p><h1 className="mt-2 text-3xl font-extrabold tracking-[-.04em]">Create your Masanawa account</h1><p className="muted mt-2 text-sm">One account for payments, digital services and provider-backed digital assets.</p>{params.error&&<div className="mt-5 rounded-2xl border border-rose-400/20 bg-rose-400/8 px-4 py-3 text-sm text-rose-200">{params.error}</div>}{referralCode&&<div className="mt-5 rounded-2xl border border-cyan-300/15 bg-cyan-300/[.05] px-4 py-3 text-xs text-cyan-100">Referral code <span className="font-bold text-cyan-300">{referralCode}</span> will be attached to your account after signup.</div>}<form action={register} className="mt-8 space-y-4"><Field name="full_name" label="Full name" placeholder="Your full name" icon={UserRound}/><Field name="email" label="Email address" placeholder="you@example.com" type="email" icon={Mail}/><Field name="password" label="Password" placeholder="At least 8 characters" type="password" icon={LockKeyhole}/><Field name="referral_code" label="Referral code (optional)" placeholder="Enter referral code" icon={Gift} defaultValue={referralCode} required={false}/><label className="flex gap-3 text-xs leading-5 text-slate-400"><input required type="checkbox" className="mt-1 accent-cyan-300"/><span>I agree to the <Link href="/terms" target="_blank" className="font-semibold text-cyan-300 hover:underline">Terms of Service</Link> and <Link href="/privacy" target="_blank" className="font-semibold text-cyan-300 hover:underline">Privacy Notice</Link>.</span></label><button type="submit" className="flex h-13 w-full items-center justify-center gap-2 rounded-2xl bg-cyan-300 text-sm font-bold text-slate-950 transition hover:bg-cyan-200">Create account <ArrowRight size={17}/></button></form><p className="muted mt-8 text-center text-sm">Already have an account? <Link href="/login" className="font-semibold text-cyan-300">Sign in</Link></p></div></section>
    <section className="relative hidden min-h-screen overflow-hidden border-l border-white/7 bg-[#091726] p-12 lg:flex lg:flex-col lg:justify-between"><Link href="/" className="flex items-center gap-3"><img src="/masanawa-mark.svg" alt="" className="h-11 w-11"/><div><p className="text-lg font-extrabold">Masanawa</p><p className="muted text-[10px] uppercase tracking-[.18em]">Pay · Trade · Connect</p></div></Link><div className="relative max-w-xl"><div className="mb-6 flex h-14 w-14 items-center justify-center rounded-3xl bg-cyan-300/10 text-cyan-300"><ShieldCheck size={25}/></div><h2 className="text-4xl font-extrabold tracking-[-.045em]">Built for everyday money.</h2><p className="muted mt-4 text-sm leading-7">Fund your wallet, transfer money, buy airtime and data, settle bills and access supported digital assets without juggling multiple services.</p><div className="mt-8 grid grid-cols-2 gap-4"><InfoCard value="Wallet" label="Ledger-backed balances"/><InfoCard value="Secure" label="Transaction PIN protection"/><InfoCard value="Clear" label="Receipts and history"/><InfoCard value="One" label="Unified account experience"/></div></div><p className="muted text-xs">© {new Date().getFullYear()} Masanawa.</p></section>
  </main>;
}
function Field({name,label,placeholder,type="text",icon:Icon,defaultValue="",required=true}:{name:string;label:string;placeholder:string;type?:string;icon:typeof Mail;defaultValue?:string;required?:boolean}){return <div><label htmlFor={name} className="mb-2 block text-xs font-semibold text-slate-300">{label}</label><div className="flex h-13 items-center gap-3 rounded-2xl border border-white/9 bg-white/[.035] px-4 focus-within:border-cyan-300/35"><Icon size={17} className="text-slate-500"/><input id={name} name={name} required={required} type={type} defaultValue={defaultValue} placeholder={placeholder} autoCapitalize={name==="referral_code"?"characters":undefined} autoComplete={name==="email"?"email":name==="password"?"new-password":undefined} className="h-full min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-slate-600"/></div></div>}
function InfoCard({value,label}:{value:string;label:string}){return <div className="rounded-[26px] border border-white/8 bg-white/[.035] p-5"><p className="text-lg font-extrabold text-cyan-300">{value}</p><p className="muted mt-2 text-xs">{label}</p></div>}
