import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft, LockKeyhole } from "lucide-react";
import { createClient } from "../../lib/supabase/server";
import { completePasswordReset } from "../auth/actions";

export const metadata = { title: "Choose new password" };
export default async function ResetPasswordPage({searchParams}:{searchParams?:Promise<{error?:string}>}) {
  const params=(await searchParams)??{}; const supabase=await createClient(); const {data:claimsData}=await supabase.auth.getClaims();
  if(!claimsData?.claims?.sub) redirect(`/forgot-password?error=${encodeURIComponent("Request a valid password reset link first.")}`);
  return <main className="min-h-screen px-5 py-8 sm:px-8"><div className="mx-auto flex min-h-[calc(100vh-4rem)] max-w-md items-center"><div className="w-full"><Link href="/" className="mb-8 flex items-center gap-2.5"><img src="/masanawa-mark.svg" alt="" className="h-9 w-9"/><span className="text-base font-extrabold">Masanawa</span></Link><Link href="/login" className="muted inline-flex items-center gap-2 text-sm hover:text-white"><ArrowLeft size={17}/>Back to sign in</Link><div className="mt-10 flex h-12 w-12 items-center justify-center rounded-2xl bg-cyan-300/10 text-cyan-300"><LockKeyhole size={22}/></div><h1 className="mt-5 text-3xl font-extrabold tracking-[-.04em]">Choose a new password</h1><p className="muted mt-2 text-sm">Your recovery link has been verified.</p>{params.error&&<div className="mt-5 rounded-2xl border border-rose-400/20 bg-rose-400/8 px-4 py-3 text-sm text-rose-200">{params.error}</div>}<form action={completePasswordReset} className="panel mt-7 space-y-5 rounded-[30px] p-5 md:p-6"><div><label htmlFor="password" className="text-xs font-semibold">New password</label><input id="password" name="password" type="password" autoComplete="new-password" required minLength={8} className="mt-3 w-full rounded-2xl border border-white/8 bg-white/[.035] px-4 py-3.5 text-sm outline-none focus:border-cyan-300/30"/></div><div><label htmlFor="confirm_password" className="text-xs font-semibold">Confirm password</label><input id="confirm_password" name="confirm_password" type="password" autoComplete="new-password" required minLength={8} className="mt-3 w-full rounded-2xl border border-white/8 bg-white/[.035] px-4 py-3.5 text-sm outline-none focus:border-cyan-300/30"/></div><button className="w-full rounded-2xl bg-cyan-300 py-3.5 text-sm font-bold text-slate-950">Update password</button></form></div></div></main>;
}
