import Link from "next/link";
import { ArrowRight, Bitcoin, Gift, Landmark, Phone, ReceiptText, Send, Tv, WalletCards, Wifi, Zap } from "lucide-react";
import { PublicPage } from "../components/PublicChrome";

export const metadata = { title: "Products & Services", description: "Explore Masanawa wallet, transfers, digital services, rewards and digital assets." };

const serviceRows = [
  [Phone,"Airtime","Recharge supported mobile numbers from your Masanawa wallet."],
  [Wifi,"Data","Choose active provider data products from the verified service catalog."],
  [Zap,"Electricity","Pay supported electricity products when a verified provider route is active."],
  [Tv,"Cable TV","Renew supported television subscriptions from one transaction flow."],
] as const;

export default function ProductsPage(){return <PublicPage>
  <section className="mx-auto max-w-7xl px-5 py-16 md:px-8 lg:py-24"><div className="max-w-3xl"><h1 className="text-4xl font-extrabold tracking-[-.05em] md:text-5xl">One account, several useful money tools.</h1><p className="muted mt-6 text-base leading-8">Masanawa combines a ledger-backed wallet, internal transfers, provider-backed withdrawals, everyday services, referrals and supported digital assets in one consistent product experience.</p></div>
  <div className="mt-14 grid gap-4 md:grid-cols-2"><Feature icon={WalletCards} title="Wallet" text="Fund your account, see your ledger-backed balance and review every transaction from one place."/><Feature icon={Send} title="Transfers" text="Send money to Masanawa usernames with transaction-PIN authorization and real transaction receipts."/><Feature icon={Landmark} title="Funding & withdrawals" text="Use configured payment-provider checkout, dedicated virtual accounts and provider-backed bank payouts."/><Feature icon={Bitcoin} title="Digital assets" text="Hold supported BTC, ETH and USDT balances and use buy, sell or swap only when a verified liquidity path is enabled."/></div></section>
  <section id="services" className="border-y border-white/6 bg-[#081522]"><div className="mx-auto max-w-7xl px-5 py-16 md:px-8 lg:py-20"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><h2 className="text-3xl font-extrabold tracking-[-.04em]">Everyday digital services.</h2><p className="muted mt-4 text-sm leading-7">Service products are activated only after they are mapped to a working provider route. If a product cannot be verified safely, Masanawa keeps it unavailable instead of showing a fake purchase flow.</p></div><div className="divide-y divide-white/7 rounded-[28px] border border-white/7 bg-white/[.025] px-5">{serviceRows.map(([Icon,title,text])=><div key={title} className="flex gap-4 py-5"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-cyan-300/9 text-cyan-300"><Icon size={18}/></div><div><h3 className="text-sm font-bold">{title}</h3><p className="muted mt-1 text-xs leading-6">{text}</p></div></div>)}</div></div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-16 md:px-8 lg:py-24"><div className="grid gap-5 lg:grid-cols-2"><Feature icon={Gift} title="Referrals & rewards" text="Share a unique referral link, track qualification status and receive rewards only through the server-side reward ledger."/><Feature icon={ReceiptText} title="Receipts & history" text="Search transactions, filter activity, open detailed receipts and export account transaction history when needed."/></div><div className="mt-12 rounded-[32px] border border-cyan-300/15 bg-cyan-300/[.045] p-7 text-center md:p-10"><h2 className="text-2xl font-extrabold tracking-[-.03em]">Ready to open Masanawa?</h2><p className="muted mx-auto mt-3 max-w-xl text-sm leading-7">Create an account and use the dashboard to see which services are active in the current environment.</p><Link href="/register" className="mt-6 inline-flex items-center gap-2 rounded-2xl bg-cyan-300 px-5 py-3 text-sm font-bold text-slate-950">Create account <ArrowRight size={15}/></Link></div></section>
</PublicPage>}

function Feature({icon:Icon,title,text}:{icon:typeof WalletCards;title:string;text:string}){return <article className="rounded-[28px] border border-white/7 bg-white/[.025] p-6"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-cyan-300/9 text-cyan-300"><Icon size={20}/></div><h2 className="mt-5 text-lg font-bold">{title}</h2><p className="muted mt-2 text-sm leading-7">{text}</p></article>}
