import Link from "next/link";
import { ArrowRight, Fingerprint, KeyRound, Landmark, LockKeyhole, ScrollText, ShieldCheck } from "lucide-react";
import { PublicPage } from "../components/PublicChrome";

export const metadata = { title: "Perfect Naira Security", description: "Learn about Perfect Naira account, wallet and transaction security controls." };
const controls = [
  [KeyRound,"Transaction PIN","Sensitive wallet actions require a six-digit PIN. The server stores only a one-way hash, not the original PIN."],
  [Fingerprint,"Identity and limits","Verification status is tied to database-enforced per-transaction and rolling 24-hour limits."],
  [Landmark,"Provider verification","Deposits and payouts are settled only through verified provider responses or signed webhook events."],
  [ScrollText,"Double-entry ledger","Wallet balances derive from ledger entries, and financial settlements must balance per currency."],
  [LockKeyhole,"Private credentials","Provider secrets and Supabase server credentials stay on the server and are not exposed to the browser."],
  [ShieldCheck,"Account controls","Users can manage security, sessions and account closure while operational actions remain auditable."],
] as const;
export default function SecurityPage(){return <PublicPage><section className="mx-auto max-w-7xl px-5 py-16 md:px-8 lg:py-24"><div className="max-w-3xl"><h1 className="text-4xl font-extrabold tracking-[-.05em] md:text-5xl">Security that sits inside the transaction path.</h1><p className="muted mt-6 text-base leading-8">Perfect Naira is designed so a polished interface cannot bypass the financial controls underneath it. Important restrictions live in authenticated server actions, database functions, row-level security and provider verification layers.</p></div><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{controls.map(([Icon,title,text])=><article key={title} className="rounded-[28px] border border-white/7 bg-white/[.025] p-6"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-emerald-400/9 text-emerald-400"><Icon size={20}/></div><h2 className="mt-5 text-base font-bold">{title}</h2><p className="muted mt-2 text-xs leading-6">{text}</p></article>)}</div><div className="mt-14 rounded-[30px] border border-white/7 bg-[#07271b] p-6 md:p-8"><h2 className="text-xl font-bold">Need help with account security?</h2><p className="muted mt-3 max-w-2xl text-sm leading-7">If you notice unexpected account activity, sign out of other sessions, change your password and transaction PIN, then contact support with the affected transaction reference if one exists.</p><Link href="/help" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-emerald-400">Open the help center <ArrowRight size={15}/></Link></div></section></PublicPage>}
